datasets:
  kitti: # name of the dataset builder
    data_type: images # [images|videos|features] we use features in this case for extracted video features

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /home/dzk/code/space/notebooks/train.json
          storage: kitti/annotations/train.json
        val:
          url: /home/dzk/code/space/notebooks/val.json
          storage: kitti/annotations/val.json
        test:
          url: /home/dzk/code/space/notebooks/test.json
          storage: kitti/annotations/test.json
      images:
        storage: kitti/images
